export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_REPOS_SUCCESS = "LOAD_REPOS_SUCCESS";
export const SET_LOADING_PROFILE = "SET_LOADING_PROFILE";
export const SET_LOADING_REPOS = "SET_LOADING_REPOS";
